<?php

namespace Database\Seeders;

use App\Models\Texto;
use Illuminate\Database\Seeder;

class TextoSistemaSeeder extends Seeder
{
    public function run(): void
    {
        $textos = [
            // ================= LAYOUT =================
            'layout' => [
                'site.nome' => 'Gostosuras',
                'site.slogan' => 'doces artesanais',
                'menu.conta' => 'Minha conta',
                'menu.conta_entrar' => 'Entrar',
                'menu.carrinho' => 'Carrinho',
                'menu.cardapio' => 'Cardápio',
                'loja.seletor' => 'Loja',
                'loja.seletor_label' => 'Atendendo da loja',
                'rodape.sobre' => 'Brigadeiros, chocolates e doces artesanais feitos com carinho para adoçar o seu dia.',
                'rodape.pagamentos_titulo' => 'Formas de pagamento',
                'rodape.entrega_titulo' => 'Como você prefere receber',
                'rodape.entrega_item' => 'Entrega no seu endereço',
                'rodape.retirada_item' => 'Retirada na loja',
                'rodape.direitos' => ':ano Gostosuras — feito com muito chocolate.',
            ],

            // ================= TEMAS (identidade por tema) =================
            // Cada tema tem nome/slogan/sobre/direitos próprios. A loja lê o tema
            // ativo (config `tema_loja`) e usa `tema_texto` para exibir a identidade.
            'tema' => [
                // Tema confeitaria (padrão) — guloseimas
                'guloseimas.nome' => 'Guloseimas',
                'guloseimas.slogan' => 'doces e guloseimas artesanais',
                'guloseimas.sobre' => 'Brigadeiros, chocolates e doces artesanais feitos com carinho para adoçar o seu dia.',
                'guloseimas.direitos' => ':ano Guloseimas — feito com muito chocolate.',
                'guloseimas.hero' => 'Guloseimas feitas à mão',
                'guloseimas.hero_sub' => 'Brigadeiros gourmet, chocolates cremosos e docinhos que derretem no coração. Peça online e receba em casa — ou retire na loja.',
                'guloseimas.hero_botao' => 'Ver as guloseimas',

                // Tema italiano
                'italiana.nome' => 'Trattoria Bella',
                'italiana.slogan' => 'cucina italiana artesanal',
                'italiana.sobre' => 'Massas, pizzas e risotos feitos à mão com ingredientes frescos e muito sabor.',
                'italiana.direitos' => ':ano Trattoria Bella — buon appetito!',
                'italiana.hero' => 'Cucina italiana fatta a mano',
                'italiana.hero_sub' => 'Massas frescas, pizzas no forno a lenha e risotos cremosos. Peça online e receba em casa — ou retire na loja.',
                'italiana.hero_botao' => 'Ver o cardápio',

                // Tema japonês
                'japonesa.nome' => 'Sakura Izakaya',
                'japonesa.slogan' => 'sabores do Japão',
                'japonesa.sobre' => 'Sushis, temakis e pratos japoneses preparados com peixe fresco e delicadeza.',
                'japonesa.direitos' => ':ano Sakura Izakaya — arigatou gozaimasu!',
                'japonesa.hero' => 'Sabores frescos do Japão',
                'japonesa.hero_sub' => 'Sushis, temakis e pratos japoneses feitos com peixe fresco e delicadeza. Peça online e receba em casa — ou retire na loja.',
                'japonesa.hero_botao' => 'Ver o cardápio',

                // Tema chinês
                'chinesa.nome' => 'Dragão Dourado',
                'chinesa.slogan' => 'cozinha chinesa autêntica',
                'chinesa.sobre' => 'Yakissoba, macarrão e clássicos da culinária chinesa com sabor autêntico.',
                'chinesa.direitos' => ':ano Dragão Dourado — bom apetite!',
                'chinesa.hero' => 'Cozinha chinesa autêntica',
                'chinesa.hero_sub' => 'Yakissoba, macarrão e clássicos da culinária chinesa. Peça online e receba em casa — ou retire na loja.',
                'chinesa.hero_botao' => 'Ver o cardápio',

                // Tema mexicano
                'mexicana.nome' => 'Taqueria El Sol',
                'mexicana.slogan' => 'sabores do México',
                'mexicana.sobre' => 'Tacos, burritos e pratos mexicanos vibrantes com temperos intensos.',
                'mexicana.direitos' => ':ano Taqueria El Sol — buen provecho!',
                'mexicana.hero' => 'Sabores vibrantes do México',
                'mexicana.hero_sub' => 'Tacos, burritos e pratos mexicanos com temperos intensos. Peça online e receba em casa — ou retire na loja.',
                'mexicana.hero_botao' => 'Ver o cardápio',
            ],

            // ================= VITRINE =================
            'vitrine' => [
                'titulo.pagina' => 'Doces artesanais',
                'hero.titulo' => 'Gostosuras feitas à mão',
                'hero.subtitulo' => 'Brigadeiros gourmet, chocolates cremosos e docinhos que derretem no coração. Peça online e receba em casa — ou retire na loja.',
                'hero.botao' => 'Ver as gostosuras',
                'secao.destaque' => 'Destaques da vitrine',
                'secao.categorias' => 'Escolha por categoria',
                'secao.produtos' => 'Nossas gostosuras',
                'promo.selo' => 'Promoção',
                'promo.percentual' => ':v% OFF',
                'promo.fixo' => ':v de desconto',
                'promo.detalhe_minimo' => 'Pedidos a partir de :v — use o código',
                'promo.detalhe' => 'Use o código',
                'promo.no_checkout' => 'no checkout.',
                'filtro.todos' => 'Tudo',
                'produtos.vazio' => 'A vitrine está esvaziando... novidades saindo do tacho em breve!',
                'produto.destaque' => 'Destaque',
                'produto.esgotado' => 'Esgotado',
                'produto.indisponivel' => 'Indisponível',
                'produto.ultimas' => 'Últimas :qtd unidades!',
                'botao.adicionar' => 'Adicionar',
                'botao.personalizar' => 'Personalizar',
                'modal.confirmar' => 'Adicionar ao carrinho',
                'modal.adicionais' => 'Adicionais',
                'modal.remocoes' => 'Remoções (grátis)',
                'modal.cada' => 'cada',
                'modal.vazio' => 'Este produto não tem personalizações no momento.',
                'info.pagamento.titulo' => 'Pague como preferir',
                'info.pagamento.texto' => 'Pix, cartão ou dinheiro. Online ou na entrega.',
                'info.entrega.titulo' => 'Receba em casa',
                'info.entrega.texto' => 'Entregamos no seu endereço. Taxa de entrega: :taxa.',
                'info.retirada.titulo' => 'Retire na loja',
                'info.retirada.texto' => 'Peça pelo site e retire sem fila, no horário que combinar.',
                'banner.rotulo' => 'Promoções e novidades',
                'banner.ir_para' => 'Ir ao banner',
                'js.aviso_atualizacao' => 'Valores e estoque acabaram de atualizar — vitrine renovada!',
            ],

            // ================= CARDÁPIO =================
            'cardapio' => [
                'titulo.pagina' => 'Cardápio',
                'titulo' => 'Cardápio',
                'subtitulo' => 'Escolha suas gostosuras e peça pelo site — receba em casa ou retire na loja.',
                'contador' => ':n gostosuras no cardápio',
                'vazio' => 'O cardápio está sendo preparado... novidades saindo do tacho em breve!',
                'nav.rotulo' => 'Categorias do cardápio',
                'item.singular' => 'item',
                'item.plural' => 'itens',
            ],

            // ================= CARRINHO =================
            'carrinho' => [
                'titulo.pagina' => 'Seu carrinho',
                'vazio' => 'Seu carrinho está mais doce que deveria... está vazio!',
                'botao.voltar' => 'Ver as gostosuras',
                'botao.finalizar' => 'Finalizar pedido',
                'botao.continuar' => 'Continuar comprando',
                'botao.remover' => 'Remover',
                'coluna.quantidade' => 'Quantidade',
                'resumo.titulo' => 'Resumo',
                'resumo.subtotal' => 'Subtotal',
                'resumo.nota_taxa' => 'A taxa de entrega é calculada no próximo passo.',
                'sucesso.adicionado' => 'Adicionado ao carrinho!',
                'sucesso.removido' => 'Item removido.',
                'erro.produto_indisponivel' => 'Produto indisponível.',
                'erro.indisponivel' => 'Este item está indisponível no momento.',
                'erro.esgotado' => 'Ops! Este doce esgotou.',
                'erro.estoque_insuficiente' => 'Estoque insuficiente. Restam :disponivel.',
                'erro.estoque_maximo' => 'Estoque máximo atingido.',
                'erro.estoque_flash' => 'Ops! :produto não tem estoque suficiente e ficou de fora do pedido.',
                'aviso.carrinho_vazio' => 'Seu carrinho está vazio — escolha algumas gostosuras antes de finalizar.',
                'aviso.preco_mudou' => 'O valor mudou desde que você adicionou (era :de). O pedido usa o valor atual: :para.',
                'aviso.preco_complemento' => 'O preço de uma personalização mudou — o pedido usa o valor atual.',
                'erro.complemento_invalido' => 'Uma das personalizações escolhidas não está mais disponível.',
                'comp_sem' => 'sem :nome',
            ],

            // ================= CHECKOUT =================
            'checkout' => [
                'titulo.pagina' => 'Finalizar pedido',
                'erro.titulo' => 'Confira os campos:',
                'erro.campo_obrigatorio' => 'Preencha o campo :attribute.',
                'campo.nome_cliente' => 'Nome completo',
                'campo.telefone' => 'Telefone / WhatsApp',
                'campo.email' => 'E-mail',
                'campo.troco_para' => 'Troco para',
                'erro.opcao_invalida' => 'Escolha uma opção válida.',
                'secao.dados' => 'Seus dados',
                'secao.entrega' => 'Entrega ou retirada?',
                'secao.pagamento' => 'Pagamento',
                'entrega.opcao_entrega' => 'Receber em casa',
                'entrega.opcao_entrega_nota' => 'Taxa de entrega: :taxa',
                'entrega.opcao_retirada' => 'Retirar na loja',
                'entrega.opcao_retirada_nota' => 'Sem taxa de entrega',
                'entrega.nota_retirada' => 'Combinaremos o horário da retirada pelo WhatsApp após a confirmação do pedido.',
                'endereco.salvo_titulo' => 'Enviar para um endereço salvo',
                'endereco.outro' => 'Usar outro endereço',
                'campo.rua' => 'Rua',
                'campo.numero' => 'Número',
                'campo.complemento' => 'Complemento',
                'campo.bairro' => 'Bairro',
                'campo.cidade' => 'Cidade',
                'campo.cep' => 'CEP',
                'campo.observacoes' => 'Observações (opcional)',
                'pagamento.pix_nota' => 'Chave Pix exibida na confirmação do pedido.',
                'pagamento.pix_efi_nota' => 'Pix na hora: geramos o copia e cola na confirmação e confirmamos sozinhos quando você pagar.',
                'pagamento.cartao_mp_nota' => 'Você será levado à tela segura do Mercado Pago — cartão, Pix ou saldo.',
                'pagamento.cartao_nota' => 'Online com cartão salvo ou combinado com você.',
                'pagamento.dinheiro_nota' => 'Pague na entrega/retirada.',
                'pagamento.cartao_salvo_titulo' => 'Pagar com um cartão salvo',
                'pagamento.cartao_selecione' => 'Selecione o cartão...',
                'pagamento.troco_para' => 'Precisa de troco para quanto?',
                'resumo.titulo' => 'Resumo do pedido',
                'resumo.taxa_entrega' => 'Taxa de entrega',
                'resumo.total' => 'Total',
                'resumo.desconto' => 'Desconto (cupom)',
                'cupom.titulo' => 'Cupom de desconto',
                'cupom.placeholder' => 'Ex.: FESTA10',
                'cupom.aplicar' => 'Aplicar',
                'cupom.vazio' => 'Digite o código do cupom.',
                'cupom.erro_rede' => 'Não foi possível validar o cupom agora.',
                'aviso.preco_atualizado' => 'Atenção: o valor de algum item mudou desde que você adicionou. O pedido abaixo usa sempre o valor atual do sistema — nada é cobrado com preço antigo.',
                'aviso.carrinho_vazio' => 'Seu carrinho está vazio — escolha algumas gostosuras antes de finalizar.',
                'botao.confirmar' => 'Confirmar pedido',
            ],

            // ================= CONFIRMAÇÃO =================
            'confirmacao' => [
                'titulo.pagina' => 'Pedido confirmado',
                'titulo' => 'Pedido confirmado!',
                'mensagem' => 'Suas gostosuras já estão na fila do tacho. Em breve entraremos em contato para confirmar tudo.',
                'codigo.rotulo' => 'Código do pedido',
                'chave_seguranca.titulo' => 'Não esqueça sua chave de segurança',
                'chave_seguranca.texto' => 'Informe a chave que você cadastrou ao receber o pedido. Assim garantimos que as gostosuras chegaram até você.',
                'resumo.titulo' => 'Resumo',
                'pix.instrucao' => 'Faça o Pix de :valor usando a chave abaixo e envie o comprovante pelo WhatsApp.',
                'pix.valor' => 'Valor: :valor',
                'cartao.salvo' => 'Usaremos o cartão salvo da sua conta. Confirmaremos a cobrança pelo WhatsApp antes de preparar.',
                'cartao.manual' => 'Combinaremos o pagamento com cartão pelo WhatsApp (maquininha na entrega ou link seguro).',
                'dinheiro.instrucao' => 'Prepare :valor para pagar na entrega/retirada.',
                'dinheiro.troco' => 'Separaremos troco para :valor.',
                'entrega.titulo' => 'Entrega',
                'retirada.titulo' => 'Retirada',
                'retirada.texto' => 'Retire na loja — combinaremos o horário pelo WhatsApp.',
                'botao.voltar' => 'Voltar à loja',
                'pagamento.pago' => 'Pagamento confirmado! Obrigado.',
                'mp.pendente' => 'Pagamento ainda não identificado no Mercado Pago.',
                'mp.pagar_agora' => 'Pagar agora no Mercado Pago',
                'efi.instrucao' => 'Pague com Pix copia e cola — a confirmação é automática quando você pagar.',
                'efi.copiar' => 'Copiar código Pix',
                'efi.copiado' => 'Copiado!',
                'efi.indisponivel' => 'Não conseguimos gerar o Pix agora — recarregue a página em alguns instantes.',
            ],

            // ================= CONTA (drawer) =================
            'conta' => [
                'titulo' => 'Minha conta',
                'fechar' => 'Fechar',
                'aba.entrar' => 'Entrar',
                'aba.criar' => 'Criar conta',
                'campo.email' => 'E-mail',
                'campo.senha' => 'Senha',
                'campo.nome' => 'Nome completo',
                'campo.telefone' => 'Telefone / WhatsApp',
                'campo.confirmar_senha' => 'Confirmar senha',
                'campo.chave_seguranca' => 'Crie sua chave (mínimo 4 caracteres)',
                'campo.confirmar_chave' => 'Confirme a chave',
                'campo.chave_atual' => 'Chave atual',
                'campo.chave_nova' => 'Nova chave',
                'campo.nova_senha' => 'Nova senha (mínimo 6 caracteres)',
                'campo.confirmar_nova' => 'Confirmar nova senha',
                'chave.titulo' => 'Chave de segurança',
                'chave.explicacao' => 'Você vai informar esta chave na entrega para confirmar que o pedido chegou até você.',
                'chave.trocar' => 'Trocar chave de segurança',
                'botao.entrar' => 'Entrar',
                'botao.criar_conta' => 'Criar minha conta',
                'botao.salvar' => 'Salvar',
                'botao.salvar_endereco' => 'Salvar endereço',
                'botao.sair' => 'Sair da conta',
                'secao.dados' => 'Dados pessoais',
                'secao.enderecos' => 'Endereços',
                'secao.cartoes' => 'Cartões',
                'secao.pedidos' => 'Meus pedidos',
                'endereco.novo_titulo' => 'Adicionar endereço',
                'endereco.principal' => 'Definir como principal',
                'cartoes.nota_seguranca' => 'Por segurança, guardamos apenas a bandeira e os 4 últimos dígitos do seu cartão.',
                'cartoes.novo_titulo' => 'Adicionar cartão',
                'cartoes.campo.apelido' => 'Apelido (ex.: Cartão do dia a dia)',
                'cartoes.campo.numero' => 'Número do cartão',
                'cartoes.campo.validade' => 'Validade (MM/AA)',
                'cartoes.campo.titular' => 'Titular',
                'cartoes.botao.salvar' => 'Salvar cartão',
                'tipo.entrega' => 'Entrega',
                'tipo.retirada' => 'Retirada',
                'js.saudacao' => 'Olá, :nome!',
                'js.remover' => 'remover',
                'js.tornar_principal' => 'principal',
                'js.endereco_vazio' => 'Nenhum endereço salvo ainda.',
                'js.cartao_vazio' => 'Nenhum cartão salvo ainda.',
                'js.pedido_vazio' => 'Você ainda não fez pedidos.',
                'js.erro_inesperado' => 'Algo saiu do ponto. Tente novamente.',
                'erro.eh_admin' => 'Este e-mail é da administração da loja. Use o painel em /admin para entrar.',
                'sucesso.registrado' => 'Conta criada com sucesso!',
                'sucesso.logado' => 'Bem-vindo de volta!',
                'sucesso.dados' => 'Dados atualizados!',
                'sucesso.endereco' => 'Endereço salvo!',
                'sucesso.endereco_removido' => 'Endereço removido.',
                'sucesso.endereco_principal' => 'Endereço principal definido.',
                'sucesso.cartao' => 'Cartão salvo!',
                'sucesso.cartao_removido' => 'Cartão removido.',
                'erro.credenciais' => 'E-mail ou senha incorretos.',
                'erro.sem_loja' => 'Nenhuma loja ativa no momento — tente de novo em instantes.',
                'erro.chave_atual' => 'Chave atual incorreta.',
                'erro.sem_permissao' => 'Este registro não pertence à sua conta.',
                'erro.campo_obrigatorio' => 'Preencha este campo.',
                'erro.campo_obrigatorio_attr' => 'Preencha o campo :attribute.',
                'erro.confirmar_senha' => 'A confirmação não conferiu.',
                'erro.senha_confirma' => 'As senhas não conferem.',
                'erro.senha_curta' => 'A senha precisa ter pelo menos 6 caracteres.',
                'erro.chave_confirma' => 'As chaves não conferem.',
                'erro.chave_min' => 'A chave deve ter no mínimo 4 caracteres.',
                'sucesso.completo' => 'Cadastro completo! Sua chave de segurança será pedida na entrega.',
                'sucesso.trocada' => 'Nova senha salva! Use-a nos próximos acessos.',
                'botao.salvar_senha' => 'Salvar nova senha',
                'botao.completar' => 'Concluir cadastro',
                'secao.senha' => 'Alterar senha',
                'social.ou' => 'ou entre com',
                'social.indisponivel' => 'Este login social não está disponível no momento.',
                'social.cancelado' => 'Login cancelado.',
                'social.estado_invalido' => 'Sessão de login expirada — tente de novo.',
                'social.erro_token' => 'O provedor recusou a conexão — tente entrar de novo.',
                'social.erro_email' => 'O provedor não compartilhou seu e-mail — use outro jeito de entrar.',
                'social.erro_conexao' => 'Não foi possível conectar ao provedor de login agora.',
                'porta.senha_titulo' => 'Troque sua senha para continuar',
                'porta.senha_nota' => 'Você entrou com a senha temporária. Crie uma nova senha de pelo menos 6 caracteres para usar nos próximos acessos.',
                'porta.completar_titulo' => 'Falta pouco para terminar seu cadastro',
                'porta.completar_nota' => 'Confirme seu telefone e crie sua chave de segurança — ela será pedida na entrega do pedido.',
            ],

            // ================= ERROS HUMANIZADOS =================
            'erros' => [
                'titulo.padrao' => 'Ops! — Gostosuras',
                'botao.voltar_loja' => 'Voltar para a loja',
                'titulo.404' => 'Página não encontrada — Gostosuras',
                'titulo_pagina.404' => 'Essa página derreteu...',
                'mensagem.404' => 'Não encontramos o que você procura. Talvez a gostosura tenha sido movida ou o link veio errado.',
                'titulo.403' => 'Acesso restrito — Gostosuras',
                'titulo_pagina.403' => 'Essa área não é sua (ainda!)',
                'mensagem.403' => 'Você não tem permissão para acessar este cantinho da confeitaria.',
                'titulo.419' => 'Sessão expirada — Gostosuras',
                'titulo_pagina.419' => 'Seu doce esfriou',
                'mensagem.419' => 'A página ficou aberta tempo demais e a sessão expirou por segurança. Atualize a página e tente de novo.',
                'titulo.500' => 'Erro inesperado — Gostosuras',
                'titulo_pagina.500' => 'Caiu açúcar no servidor',
                'mensagem.500' => 'Algo saiu do ponto na nossa cozinha e já estamos limpando a bagunça. Tente novamente em alguns instantes.',
                'titulo.503' => 'Em manutenção — Gostosuras',
                'titulo_pagina.503' => 'Estamos reabastecendo a vitrine',
                'mensagem.503' => 'A loja está em manutenção rápida. Volte em alguns minutos — as gostosuras continuam aqui.',
            ],

            // ================= RÓTULOS FIXOS =================
            'pagamentos' => [
                'forma.pix' => 'Pix',
                'forma.cartao' => 'Cartão',
                'forma.dinheiro' => 'Dinheiro',
                'forma.cartao_mp' => 'Cartão online (Mercado Pago)',
                'forma.pix_efi' => 'Pix automático',
                'mp.erro_conexao' => 'Não foi possível falar com o Mercado Pago agora — tente de novo.',
                'mp.titulo_pedido' => 'Pedido',
                'mp.erro_preferencia' => 'O Mercado Pago recusou o pagamento — confira as credenciais em Configurações.',
                'efi.erro_conexao' => 'Não foi possível falar com a Efí agora — tente de novo.',
                'efi.erro_token' => 'A Efí recusou as credenciais — confira em Configurações.',
                'efi.erro_cobranca' => 'A Efí recusou a cobrança Pix — confira as credenciais e a chave Pix em Configurações.',
            ],
            'status' => [
                'status.novo' => 'Novo',
                'status.em_preparo' => 'Em preparo',
                'status.em_entrega' => 'Em entrega',
                'status.entregue' => 'Entregue',
                'status.cancelado' => 'Cancelado',
            ],

            // ================= ADMIN: AUDITORIA =================
            'admin_auditoria' => [
                'titulo' => 'Auditoria — Gostosuras',
                'titulo.pagina' => 'Auditoria do banco',
                'titulo.detalhe' => 'Evento de auditoria — Gostosuras',
                'titulo.detalhe.pagina' => 'Evento #:id',
                'nota.imutavel' => 'Histórico imutável de tudo que é criado, alterado e excluído — inclusive edições feitas direto no banco. Para voltar um estado, abra o evento e use a restauração com a senha master.',
                'filtro.registro' => 'Id do registro ou autor...',
                'filtro.todas_tabelas' => 'Todas as tabelas',
                'filtro.todas_acoes' => 'Todas as ações',
                'filtro.todas_origens' => 'Todas as origens',
                'coluna.acao' => 'Ação',
                'coluna.registro' => 'Registro',
                'coluna.origem' => 'Origem',
                'coluna.url' => 'URL',
                'coluna.frase' => 'O que aconteceu',
                'acao.insert' => 'Criação',
                'acao.update' => 'Alteração',
                'acao.delete' => 'Exclusão',
                'origem.gatilho' => 'Banco (gatilho)',
                'origem.aplicacao' => 'Aplicação',
                'lista.vazia' => 'Nenhum evento registrado ainda.',
                'detalhe.alteracoes' => 'O que mudou',
                'detalhe.delete_explicacao' => 'Este registro foi excluído. O snapshot abaixo permite reinseri-lo exatamente como estava.',
                'detalhe.insert_explicacao' => 'Novo registro criado com os dados abaixo.',
                'detalhe.sem_dados' => 'Sem snapshot detalhado para este evento.',
                'detalhe.evento_titulo' => 'Sobre o evento',
                'diff.campo' => 'Campo',
                'diff.antes' => 'Antes',
                'diff.depois' => 'Depois',
                'restaurar.titulo' => 'Retornar a este estado',
                'restaurar.explica_insert' => 'O registro voltará ao estado em que foi criado (snapshot da criação).',
                'restaurar.explica_update' => 'O registro voltará exatamente ao estado registrado logo depois desta alteração.',
                'restaurar.explica_delete' => 'O registro excluído será trazido de volta como estava antes de ser excluído.',
                'restaurar.campo_senha' => 'Senha master',
                'restaurar.botao' => 'Retornar a este estado',
                'erro.senha_obrigatoria' => 'Informe a senha master.',
            ],

            // ================= ADMIN: BANNERS =================
            'admin_banners' => [
                'titulo' => 'Banners — Gostosuras',
                'titulo.form' => 'Banner — Gostosuras',
                'titulo.pagina' => 'Banners da vitrine',
                'form.titulo_novo' => 'Novo banner',
                'form.titulo_editar' => 'Editar banner',
                'nota.agendamento' => 'O banner entra no ar na data de início e sai na data de fim automaticamente. Deixe as datas vazias para ficar sempre no ar (enquanto estiver ligado).',
                'lista.titulo' => 'Banners cadastrados',
                'lista.sem_titulo' => 'Banner sem título',
                'lista.de' => 'De',
                'lista.ate' => 'até',
                'lista.sempre' => 'Sem agendamento — sempre no ar',
                'lista.vazia' => 'Nenhum banner cadastrado — a vitrine usa o destaque padrão.',
                'novo.titulo' => 'Novo banner',
                'novo.dica' => 'Imagem panorâmica funciona melhor (ex.: 1600×600).',
                'campo.titulo' => 'Título interno (opcional)',
                'campo.titulo_placeholder' => 'Ex.: Promoção Páscoa',
                'campo.imagem' => 'Imagem do banner',
                'campo.escolher_imagem' => 'Escolher imagem',
                'campo.trocar_imagem' => 'Trocar imagem',
                'campo.sem_arquivo' => 'Nenhuma imagem escolhida',
                'campo.imagem_atual' => 'Imagem atual',
                'campo.link' => 'Link ao clicar (opcional)',
                'campo.inicio' => 'Entrar no ar em',
                'campo.fim' => 'Sair do ar em',
                'campo.ordem' => 'Ordem de exibição',
                'campo.ativo' => 'Banner ligado',
                'form.secao.imagem' => 'Imagem',
                'form.secao.identificacao' => 'Identificação',
                'form.secao.agendamento' => 'Agendamento',
                'form.secao.exibicao' => 'Exibição',
                'botao.cancelar' => 'Cancelar',
                'botao.criar' => 'Criar banner',
                'botao.editar' => 'Editar',
                'botao.remover' => 'Remover',
                'botao.ligar_desligar' => 'Ligar ou desligar',
                'botao.salvar' => 'Salvar banner',
                'botao.confirmar_remover' => 'Remover este banner?',
                'status.no_ar' => 'No ar',
                'status.agendado' => 'Agendado',
                'status.expirado' => 'Expirado',
                'status.desligado' => 'Desligado',
                'sucesso.criado' => 'Banner criado! Entra e sai do ar conforme o agendamento.',
                'sucesso.atualizado' => 'Banner atualizado!',
                'sucesso.removido' => 'Banner removido.',
                'sucesso.ligado' => 'Banner ligado — entra no ar conforme o agendamento.',
                'sucesso.desligado' => 'Banner desligado — saiu do ar.',
                'erro.imagem_obrigatoria' => 'Escolha uma imagem para o banner.',
                'erro.imagem_invalida' => 'O arquivo precisa ser uma imagem JPG, PNG ou WEBP.',
                'erro.imagem_grande' => 'A imagem passa de 4 MB — escolha uma mais leve.',
                'erro.periodo_invalido' => 'O fim do agendamento precisa ser depois do início.',
                'erro.ordem_invalida' => 'A ordem precisa ser um número.',
            ],

            // ================= CUPOM =================
            'cupom' => [
                'campo.codigo' => 'Digite o código do cupom.',
                'erro.inexistente' => 'Cupom não encontrado.',
                'erro.inativo' => 'Este cupom não está mais ativo.',
                'erro.expirado' => 'Este cupom expirou.',
                'erro.esgotado' => 'Este cupom já foi todo usado.',
                'erro.minimo' => 'Use este cupom em pedidos a partir de :valor.',
                'erro.nulo' => 'Este cupom não gera desconto neste pedido.',
                'erro.invalido' => 'Cupom inválido ou expirado.',
            ],
            // ================= ADMIN: CUPONS =================
            'admin_cupons' => [
                'titulo' => 'Cupons — Gostosuras',
                'titulo.pagina' => 'Cupons promocionais',
                'titulo.form' => 'Cupom — Gostosuras',
                'form.titulo_novo' => 'Novo cupom',
                'form.titulo_editar' => 'Editar cupom',
                'form.secao.identificacao' => 'Identificação',
                'form.secao.desconto' => 'Desconto',
                'form.secao.restricoes' => 'Validade e limites',
                'opcao.percentual' => 'Percentual (%)',
                'opcao.fixo' => 'Valor fixo (R$)',
                'lista.titulo' => 'Cupons cadastrados',
                'lista.minimo' => 'mín. :valor',
                'lista.usos' => 'usos',
                'lista.ate_data' => 'até',
                'lista.sem_validade' => 'sem validade',
                'lista.vazia' => 'Nenhum cupom cadastrado ainda.',
                'nota.regras' => 'Um cupom só é aceito se estiver ativo, dentro da validade, com usos disponíveis e atingindo o pedido mínimo. O cupom destacado vira a promoção mostrada na vitrine e no cardápio.',
                'novo.titulo' => 'Novo cupom',
                'novo.dica' => 'Crie cupons de percentual ou valor fixo e escolha qual promover na vitrine.',
                'subtitulo' => 'Crie cupons percentuais ou de valor fixo, limite usos e escolha qual divulgar na vitrine.',
                'tabela.codigo' => 'Código',
                'tabela.desconto' => 'Desconto',
                'tabela.valor_minimo' => 'Pedido mínimo',
                'tabela.usos' => 'Usos',
                'tabela.validade' => 'Validade',
                'tabela.status' => 'Status',
                'metrica.ativos' => 'Cupons ativos',
                'botao.novo' => 'Novo cupom',
                'botao.editar' => 'Editar',
                'botao.remover' => 'Remover',
                'botao.ligar_desligar' => 'Ligar ou desligar',
                'botao.divulgar' => 'Divulgar na vitrine',
                'botao.parar_divulgacao' => 'Parar divulgação',
                'botao.salvar' => 'Salvar cupom',
                'botao.criar' => 'Criar cupom',
                'botao.cancelar' => 'Cancelar',
                'botao.confirmar_remover' => 'Remover este cupom?',
                'campo.codigo' => 'Código (use letras maiúsculas)',
                'campo.codigo_placeholder' => 'Ex.: FESTA10',
                'campo.tipo' => 'Tipo de desconto',
                'campo.tipo_percentual' => 'Percentual (%)',
                'campo.tipo_fixo' => 'Valor fixo (R$)',
                'campo.valor' => 'Valor do desconto (R$ ou %)',
                'campo.valor_minimo' => 'Pedido mínimo (opcional)',
                'campo.limite_usos' => 'Limite de usos (opcional)',
                'campo.inicio_em' => 'Começa em',
                'campo.fim_em' => 'Termina em',
                'campo.ativo' => 'Cupom ativo',
                'form.secao.desconto' => 'Desconto',
                'form.secao.restricoes' => 'Restrições e validade',
                'status.ativo' => 'Ativo',
                'status.inativo' => 'Inativo',
                'status.sem_validade' => 'Sem limite de tempo',
                'status.divulgado' => 'Divulgado na vitrine',
                'sem_cupons' => 'Nenhum cupom criado ainda.',
                'sucesso.criado' => 'Cupom criado!',
                'sucesso.atualizado' => 'Cupom atualizado!',
                'sucesso.removido' => 'Cupom removido.',
                'sucesso.ligado' => 'Cupom ativado.',
                'sucesso.desligado' => 'Cupom desativado.',
                'sucesso.divulgado' => 'Cupom divulgado na vitrine.',
                'sucesso.parar_divulgacao' => 'Cupom deixou de ser divulgado.',
                'erro.codigo_duplicado' => 'Já existe um cupom com este código.',
            ],

            // ================= FIDELIDADE (cliente) =================
            'fidelidade' => [
                'titulo' => 'Pontos de fidelidade',
                'saldo' => 'Seus pontos',
                'saldo.quantidade' => ':pontos pontos',
                'campo.pontos' => 'Quantos pontos quer usar?',
                'botao.aplicar' => 'Usar pontos',
                'ganho.este_pedido' => 'Você vai ganhar :pontos pontos com este pedido.',
                'erro.indisponivel' => 'O programa de fidelidade não está ativo.',
                'erro.sem_saldo' => 'Você não tem pontos suficientes para esse resgate.',
                'erro.nulo' => 'Esses pontos não geram desconto neste pedido.',
                'erro.zero' => 'Informe quantos pontos quer usar.',
                'erro.rede' => 'Não foi possível validar os pontos agora.',
                'sucesso.aplicado' => 'Pontos aplicados: -:valor de desconto.',
                'resumo.desconto' => 'Desconto (pontos)',
                'confirmacao.ganhou' => 'Você ganhou :pontos pontos com este pedido!',
                'confirmacao.saldo' => 'Seu saldo atual: :pontos pontos.',
                'confirmacao.usou' => 'Você usou :pontos pontos neste pedido.',
            ],

            // ================= ADMIN: FIDELIDADE =================
            'admin_fidelidade' => [
                'titulo' => 'Fidelidade — Gostosuras',
                'titulo.pagina' => 'Programa de fidelidade (pontos)',
                'secao.geral' => 'Funcionamento',
                'secao.regras' => 'Regras de ganho e resgate',
                'secao.status' => 'Status atual',
                'campo.ativo' => 'Ativar programa de fidelidade (pontos)',
                'campo.ganho' => 'Pontos por R$ 1,00 de compra',
                'campo.ponto_valor' => 'Valor de cada ponto no resgate (R$)',
                'nota.explicacao' => 'Com o módulo ativo, o cliente logado acumula pontos a cada pedido (R$ 1,00 de compra rende 1 ponto, configurável abaixo) e pode trocá-los por desconto no checkout.',
                'nota.regras' => 'Ex.: com "valor do ponto" 0,10, cada 10 pontos valem R$ 1,00 de desconto no checkout.',
                'metrica.pontos' => 'pontos em circulação',
                'metrica.clientes' => 'clientes com pontos',
                'botao.salvar' => 'Salvar fidelidade',
                'sucesso.salvo' => 'Configuração do programa de fidelidade salva!',
                 'erro.numero' => 'Informe um número válido.',
             ],

             // ================= ADMIN: LOJAS =================
             'admin_lojas' => [
                 'titulo' => 'Lojas — Gostosuras',
                 'titulo.pagina' => 'Lojas da rede',
                 'nota.explicacao' => 'Cada loja tem seu catálogo, pedidos e configurações próprios. Nosso painel filtra pelos dados da loja ativa; a loja pública pode ser trocada pelo cliente no topo da vitrine.',
                 'lista.titulo' => 'Lojas cadastradas',
                 'lista.vazia' => 'Nenhuma loja cadastrada ainda.',
                 'lista.ativa' => 'ativa',
                 'metrica.produtos' => 'produtos',
                 'metrica.pedidos' => 'pedidos',
                 'novo.titulo' => 'Nova loja',
                 'novo.dica' => 'Crie uma loja da rede: ela começa com o catálogo vazio e usa os textos e configurações padrão da matriz.',
                 'botao.criar' => 'Criar loja',
                 'botao.editar' => 'Editar',
                 'botao.trocar' => 'Tornar ativa',
                 'botao.salvar' => 'Salvar loja',
                 'botao.cancelar' => 'Cancelar',
                 'botao.suspender_ativar' => 'Suspender ou ativar',
                 'campo.nome' => 'Nome da loja',
                 'campo.slug' => 'Identificador (usado no QR e nos relatórios)',
                 'campo.dominio' => 'Domínio próprio (opcional — vazio = loja no domínio principal)',
                 'campo.status' => 'Situação',
                 'opcao.ativo' => 'Ativa (aparece no seletor)',
                 'opcao.suspenso' => 'Suspensa (oculta)',
                 'form.secao.dados' => 'Dados da loja',
                 'sucesso.criado' => 'Loja criada!',
                 'sucesso.atualizado' => 'Loja atualizada!',
                 'sucesso.trocada' => 'Você está na loja :nome.',
                 'sucesso.ativa' => 'Loja ativada — aparece no seletor dos clientes.',
                 'sucesso.suspensa' => 'Loja suspensa — não aparece para os clientes.',
                 'erro.obrigatorio' => 'Escolha uma opção válida.',
                 'erro.nome_obrigatorio' => 'Informe o nome da loja.',
                 'erro.slug_obrigatorio' => 'Informe o identificador da loja.',
                 'erro.slug_invalido' => 'Use apenas letras minúsculas, números e hífen.',
                 'erro.slug_duplicado' => 'Já existe uma loja com esse identificador.',
                 'erro.dominio_duplicado' => 'Já existe uma loja com esse domínio.',
                 'erro.suspensa' => 'Essa loja está suspensa.',
                 'status.ativo' => 'Ativa',
                 'status.suspenso' => 'Suspensa',
                 'confirm.trocar' => 'Trocando de loja recarrega a página e atualiza preços e disponibilidade. Continuar?',
             ],

             // ================= ADMIN: MESAS =================
             'admin_mesas' => [
                 'titulo' => 'Mesas — Gostosuras',
                 'titulo.pagina' => 'Mesas da loja',
                 'titulo.form' => 'Mesa — Gostosuras',
                 'nota.explicacao' => 'Cada mesa tem um QR code que abre o cardápio já vinculado a ela. Os pedidos feitos por esse cardápio caem direto na fila da cozinha com o número da mesa.',
                 'lista.titulo' => 'Mesas cadastradas',
                 'lista.vazia' => 'Nenhuma mesa cadastrada ainda. Crie a primeira para gerar o QR code e começar a receber pedidos por mesa.',
                 'lista.codigo' => 'código',
                 'lista.pessoa_singular' => 'pessoa',
                 'lista.pessoa_plural' => 'pessoas',
                 'novo.titulo' => 'Nova mesa',
                 'novo.dica' => 'Dê um nome (ex.: Mesa 1, Varanda, Balcão 2) e a capacidade. O QR code fica disponível na tela de Configurações, já apontando para o cardápio desta mesa.',
                 'form.titulo_novo' => 'Nova mesa',
                 'form.titulo_editar' => 'Editar mesa',
                 'form.secao.identificacao' => 'Identificação',
                 'form.secao.detalhes' => 'Detalhes',
                 'campo.nome' => 'Nome (ex.: Mesa 1, Varanda)',
                 'campo.codigo' => 'Código (opcional, usado em relatórios e no QR)',
                 'campo.capacidade' => 'Capacidade (pessoas)',
                 'campo.ativo' => 'Mesa ativa',
                 'botao.criar' => 'Criar mesa',
                 'botao.editar' => 'Editar',
                 'botao.qr' => 'Ver QR',
                 'botao.salvar' => 'Salvar mesa',
                 'botao.cancelar' => 'Cancelar',
                 'botao.ligar_desligar' => 'Ativar ou desativar mesa',
                 'sucesso.criado' => 'Mesa criada!',
                 'sucesso.atualizado' => 'Mesa atualizada!',
                 'sucesso.ativa' => 'Mesa ativada',
                 'sucesso.inativa' => 'Mesa inativada',
                 'erro.nome_obrigatorio' => 'Informe o nome da mesa.',
                 'erro.codigo_duplicado' => 'Já existe uma mesa com esse código.',
                 'erro.capacidade_min' => 'A capacidade deve ser de pelo menos 1 pessoa.',
                 'erro.capacidade_max' => 'A capacidade máxima é de 20 pessoas.',
                 'status.ativa' => 'Ativa',
                 'status.inativa' => 'Inativa',
             ],

             // ================= ADMIN: CONTROLE DE PEDIDOS DAS MESAS =================
             'admin_mesas_controle' => [
                 'titulo' => 'Pedidos das mesas — Gostosuras',
                 'titulo.pagina' => 'Pedidos das mesas (tempo real)',
                 'nota.explicacao' => 'A grade mostra cada mesa ativa com o(s) pedido(s) em aberto. Quando chega um pedido novo, o quadro pisca em vermelho e toca um alerta — abra o pedido para começar o preparo.',
                 'controle.som' => 'Tocar som de alerta',
                 'controle.testar_som' => 'Testar som',
                 'controle.conectado' => 'Conectado',
                 'estado.livre' => 'Livre',
                 'estado.novo' => 'Aguardando preparo',
                 'estado.em_preparo' => 'Em preparo',
                 'estado.em_entrega' => 'Sendo entregue',
                 'pessoa.singular' => 'pessoa',
                 'pessoa.plural' => 'pessoas',
                 'popup.titulo' => 'Novo pedido!',
                 'popup.mesa' => 'Mesa',
                 'popup.codigo' => 'Código',
                 'popup.cliente' => 'Cliente',
                 'popup.total' => 'Total',
                 'popup.abrir' => 'Abrir pedido',
                 'popup.fechar' => 'Fechar',
                 'cartao.abrir' => 'Abrir mesa',
                 'modal.fechar' => 'Fechar',
                 'modal.carregando' => 'Carregando pedidos da mesa...',
                 'modal.vazio' => 'Esta mesa está livre — nenhum pedido em aberto.',
                 'modal.pedidos_abertos' => 'pedidos em aberto',
                 'modal.observacoes' => 'Observações',
                 'modal.total_mesa' => 'Total da mesa',
                 'modal.abrir_pedido' => 'Abrir pedido',
                 'modal.pagamento' => 'Pagamento',
                 'modal.horario' => 'Hora',
                 'modal.itens' => 'item(ns)',
                 'vazio' => 'Nenhuma mesa ativa cadastrada. Vá em Mesas e ative ao menos uma para começar.',
             ],

             // ================= ADMIN: CLIENTES =================
             'admin_clientes' => [
                'titulo' => 'Clientes — Gostosuras',
                'titulo.pagina' => 'Clientes cadastrados',
                'metrica.total' => 'Clientes com conta',
                'metrica.com_pedidos' => 'Já compraram',
                'metrica.novos_mes' => 'Novos neste mês',
                'campanha.titulo' => 'Enviar oferta / mensagem no WhatsApp',
                'campanha.nota' => 'Escreva a mensagem, escolha os clientes (nada selecionado = todos) e abrirá a conversa pronta no WhatsApp — você só aperta enviar. Use :nome para chamar cada cliente pelo primeiro nome.',
                'campanha.placeholder' => 'Ex.: Olá :nome! Hoje os brigadeiros gourmet estão com 20% OFF — peça pelo site!',
                'campanha.botao' => 'Abrir WhatsApp dos selecionados',
                'campanha.lista_titulo' => 'Lista de envio',
                'campanha.selecionar_todos' => 'Selecionar todos',
                'campanha.nota_todos' => 'Nada marcado = envia para todos.',
                'campanha.contador_marcados' => ':qtd selecionado(s) para receber a oferta',
                'campanha.contador_todos' => 'Todos os :qtd clientes vão receber',
                'campanha.status_api' => 'API do WhatsApp: :enviados de :qtd mensagem(ns) enviada(s) com sucesso.',
                'lista.titulo' => 'Contas cadastradas',
                'lista.nota_privacidade' => 'Senhas e chaves de segurança nunca são exibidas. A opção de senha gera uma nova senha temporária e prepara a mensagem no WhatsApp.',
                'lista.vazia' => 'Nenhum cliente com conta ainda.',
                'coluna.nome' => 'Cliente',
                'coluna.contato' => 'Contato',
                'coluna.incluir' => 'Incluir na oferta',
                'coluna.desde' => 'Cliente desde',
                'coluna.pedidos' => 'Pedidos',
                'coluna.total_gasto' => 'Total comprado',
                'coluna.acoes' => 'Ações',
                'botao.senha_whats' => 'Nova senha no WhatsApp',
                'botao.selecionar' => 'selecionar',
                'whats.mensagem_senha' => 'Olá :nome! Sua nova senha de acesso à loja Gostosuras é: :senha. Recomendamos trocá-la após entrar.',
                'sucesso.senha' => 'Nova senha gerada para :nome.',
                'sucesso.senha_api' => 'Senha redefinida e enviada pelo WhatsApp para :nome.',
                'aviso.senha_api' => 'Senha redefinida, mas o envio falhou (:motivo) — abra o link pronto.',
                'erro.mensagem' => 'Escreva a mensagem da oferta.',
                'erro.mensagem_curta' => 'A mensagem está muito curta.',
                'js.confirmar_senha' => 'Gerar uma NOVA senha para este cliente? A antiga deixa de funcionar e a mensagem do WhatsApp será aberta.',
                'js.mensagem_curta' => 'Escreva a mensagem da oferta primeiro.',
                'js.abrindo' => 'Abrindo :qtd conversa(s) no WhatsApp...',
                'js.aberto' => ':qtd conversa(s) aberta(s) no WhatsApp — basta apertar enviar em cada uma.',
                'js.erro_popup' => 'O navegador bloqueou as janelas do WhatsApp — permita pop-ups para este site e tente de novo.',
            ],

            // ================= ADMIN: CONFIGURAÇÕES =================
            'admin_config' => [
                'titulo' => 'Configurações — Gostosuras',
                'titulo.pagina' => 'Configurações da loja',
                'secao.loja' => 'Loja',
                'secao.cardapio' => 'Cardápio digital',
                'nota.cardapio' => 'Este é o seu cardápio digital aberto a todos os clientes. Ele mostra os produtos ativos, organizados por categoria, e permite pedir direto de lá (mesmo carrinho e checkout da loja).',
                'cardapio.ver' => 'Ver cardápio',
                'cardapio.copiar' => 'Copiar link',
                'cardapio.url_rotulo' => 'Link do cardápio',
                'cardapio.qr_alt' => 'QR code do cardápio digital',
                'cardapio.qr_nota' => 'Imprima e coloque na mesa ou balcão: o cliente aponta a câmera e abre o cardápio.',
                'secao.nfe' => 'Nota fiscal (NF-e / NFC-e)',
                'campo.taxa_entrega' => 'Taxa de entrega (R$)',
                'campo.margem' => 'Margem de produção (%) — previsão por horário',
                'campo.chave_pix' => 'Chave Pix exibida ao cliente',
                'campo.emitir_nfe' => 'Habilitar emissão de nota fiscal nos pedidos',
                'campo.cnpj' => 'CNPJ da empresa',
                'campo.ie' => 'Inscrição Estadual',
                'campo.razao' => 'Razão social',
                'campo.ambiente' => 'Ambiente SEFAZ',
                'ambiente.homologacao' => 'Homologação (testes)',
                'ambiente.producao' => 'Produção',
                'nota.nfe' => 'Com a emissão habilitada, cada pedido ganha o botão "Gerar NF", que registra a nota como PENDENTE. A transmissão real à SEFAZ exige: certificado digital A1 (.env: NFE_CERT_PATH e NFE_CERT_SENHA), CNPJ da empresa abaixo e dados fiscais dos produtos (NCM/CFOP). As libs sped-nfe e sped-da já estão instaladas.',
                'botao.salvar' => 'Salvar configurações',
                'sucesso.salvo' => 'Configurações salvas!',
                'erro.numero' => 'Informe um número válido.',
                'secao.whatsapp' => 'WhatsApp (envio automático pela API oficial)',
                'campo.whatsapp_ativo' => 'Enviar ofertas e senhas pela API oficial (sem abrir janelas)',
                'nota.whatsapp' => 'Requer uma conta WhatsApp Business na Meta Cloud API. Preencha o token permanente e o Phone Number ID. Dentro da janela de 24h do cliente o texto livre é aceito; fora dela a Meta exige template aprovado — nesse caso o painel cai no modo link automaticamente.',
                'campo.whatsapp_token' => 'Token permanente (access token)',
                'campo.whatsapp_phone_id' => 'Phone Number ID',
                'secao.google' => 'Login social com Google',
                'campo.google_ativo' => 'Mostrar o botão "Entrar com Google" na loja',
                'nota.google' => 'Crie um OAuth Client (tipo Web) no console do provedor e cadastre a URI de retorno: :callback',
                'campo.google_id' => 'Client ID',
                'campo.google_secret' => 'Client secret',
                'campo.facebook_ativo' => 'Mostrar o botão "Entrar com Facebook" na loja',
                'campo.facebook_id' => 'App ID (Facebook)',
                'campo.facebook_secret' => 'App secret (Facebook)',
                'campo.microsoft_ativo' => 'Mostrar o botão "Entrar com Microsoft" na loja',
                'campo.microsoft_id' => 'Application (client) ID — Microsoft',
                'campo.microsoft_secret' => 'Client secret — Microsoft',
                'secao.pagamentos' => 'Pagamento online',
                'campo.mercadopago_ativo' => 'Aceitar cartão online via Mercado Pago (Checkout Pro)',
                'nota.mercadopago' => 'Crie uma aplicação em developers.mercadopago.com, copie o Access Token e cole abaixo. Com credenciais de TESTE o fluxo inteiro funciona em sandbox; para vender de verdade troque pelas credenciais de produção. Sem mensalidade — você paga taxa só por venda.',
                'campo.mercadopago_token' => 'Access Token',
                'campo.mercadopago_public_key' => 'Public Key (opcional)',
                'campo.efi_ativo' => 'Aceitar Pix automático via Efí (copia e cola na hora)',
                'nota.efi' => 'Crie um aplicativo em seuefi.com (produtos: Pix) e copie Client ID e Client Secret. Informe também a chave Pix cadastrada no app. O recebimento Pix na Efí é gratuito; em homologação os pagamentos são simulados.',
                'campo.efi_client_id' => 'Client ID',
                'campo.efi_client_secret' => 'Client Secret',
                'campo.efi_pix_chave' => 'Chave Pix do recebimento',
                'campo.efi_sandbox' => 'Homologação (testes) — desligue para produção',
                'passo.mp.1' => 'Crie o app em developers.mercadopago.com',
                'passo.mp.2' => 'Copie o Access Token de teste (começa com TEST-)',
                'passo.mp.3' => 'Cole no campo abaixo, marque a flag e salve',
                'passo.mp.4' => 'No painel do Mercado Pago, cadastre a URL de notificação: :url',
                'passo.efi.1' => 'Crie o app em seuefi.com com o produto Pix',
                'passo.efi.2' => 'Copie Client ID/Secret de homologação e cadastre uma chave Pix',
                'passo.efi.3' => 'Cole nos campos abaixo, marque a flag (com "Homologação") e salve',
                'passo.efi.4' => 'No painel da Efí, cadastre a URL de notificação: :url',
                'secao.item_venda' => 'Produtos e serviços (item-venda)',
                'nota.item_venda' => 'Controle geral do módulo de produtos e serviços. Os detalhes ficam na tela própria do módulo no menu.',
                'campo.item_venda_ativo' => 'Ativar cadastro de produtos e serviços',
                'secao.tema' => 'Tema da loja',
                'nota.tema' => 'Muda as cores e a identidade da loja (nome, slogan e rodapé). O tema também vale para o cardápio.',
                'campo.tema_loja' => 'Tema ativo',
            ],

            // ================= ADMIN: MÓDULO PRODUTOS E SERVIÇOS (item-venda) =================
            'admin_item_venda' => [
                'titulo' => 'Produtos e serviços — Gostosuras',
                'titulo.pagina' => 'Módulo de produtos e serviços',
                'secao.geral' => 'Módulo',
                'campo.ativo' => 'Ativar cadastro de produtos e serviços',
                'nota.geral' => 'Com o módulo ativo, o sistema gerencia produtos (quantidade inteira ou fracionada) e serviços (cobrança por serviço ou por hora) usando a biblioteca item-venda.',
                'secao.resumo' => 'Resumo atual',
                'metrica.produtos' => 'produtos cadastrados',
                'metrica.ativos' => 'produtos ativos na vitrine',
                'metrica.categorias' => 'categorias',
                'metrica.pedidos' => 'pedidos com itens',
                'botao.salvar' => 'Salvar módulo',
                'campo.tipo' => 'O que o sistema vende',
                'tipo.produtos' => 'Apenas produtos',
                'tipo.servicos' => 'Apenas serviços',
                'tipo.ambos' => 'Produtos e serviços',
                'nota.somente_produtos' => 'Venda configurada apenas para produtos — o padrão deste delivery.',
                'nota.somente_servicos' => 'Este delivery ainda não tem cadastro de serviços na vitrine/carrinho. Ao configurar "apenas serviços", o painel de produtos fica oculto até a venda de serviços ser integrada.',
                'nota.ambos' => 'Venda configurada para produtos e serviços. O cadastro de serviços ainda não está integrado à vitrine/carrinho deste delivery.',
                'sucesso.salvo' => 'Módulo de produtos e serviços atualizado!',
            ],

            // ================= ADMIN: PWA =================
            'admin_pwa' => [
                'titulo' => 'PWA / App — Gostosuras',
                'titulo.pagina' => 'Módulo PWA (app / cardápio offline)',
                'secao.geral' => 'App instalável',
                'campo.ativo' => 'Ativar PWA (cardápio consultável offline e instalável no celular)',
                'nota.explicacao' => 'Com o PWA ativo, o cliente visita o cardápio uma vez e depois consegue consultá-lo mesmo sem internet, além de poder instalar o atalho na tela inicial do celular.',
                'secao.status' => 'Status atual',
                'metrica.imagens' => 'imagens guardadas para consulta offline',
                'metrica.cache' => 'versão do cache do app',
                'campo.renovar' => 'Renovar agora o cache dos clientes (recarregar cardápio/preços na próxima abertura)',
                'secao.links' => 'Links do app',
                'link.cardapio' => 'Ver o cardápio que fica disponível offline',
                'link.sw_nome' => 'service worker',
                'link.manifest_nome' => 'manifesto do app',
                'botao.salvar' => 'Salvar app (PWA)',
                'sucesso.salvo' => 'Configuração do app (PWA) salva!',
            ],

            // ================= ADMIN: LAYOUT / LOGIN =================
            'admin_layout' => [
                'categoria.vendas' => 'Vendas',
                'categoria.catalogo' => 'Catálogo',
                'categoria.promocao' => 'Promoção',
                'categoria.sistema' => 'Sistema',
                'menu.auditoria' => 'Auditoria',
                'menu.banners' => 'Banners',
                'menu.cupons' => 'Cupons',
                'menu.fidelidade' => 'Fidelidade',
                'titulo' => 'Painel — Gostosuras',
                'marca.painel' => 'painel',
                'menu.dashboard' => 'Dashboard',
                'menu.pedidos' => 'Pedidos',
                'menu.produtos' => 'Produtos e estoque',
                'menu.relatorios' => 'Relatórios',
                'menu.clientes' => 'Clientes',
                'menu.configuracoes' => 'Configurações',
                'menu.item_venda' => 'Produtos e serviços',
                'menu.pwa' => 'PWA / App',
                'menu.help' => 'Ajuda',
                'menu.ver_loja' => 'Ver loja',
                'menu.lojas' => 'Lojas',
                'menu.mesas' => 'Mesas (QR)',
                'menu.mesas_controle' => 'Pedidos das mesas',
                'loja.atual' => 'Loja ativa',
                'loja.trocar' => 'Trocar',
                'categoria.multiloja' => 'Rede',
            ],
            'admin_login' => [
                'titulo' => 'Entrar no painel — Gostosuras',
                'subtitulo' => 'Acesso restrito à administração',
                'campo.email' => 'E-mail',
                'campo.senha' => 'Senha',
                'campo.lembrar' => 'Manter conectado',
                'botao.entrar' => 'Entrar',
                'erro.campo_obrigatorio' => 'Preencha este campo.',
                'erro.email_invalido' => 'Informe um e-mail válido.',
                'erro.credenciais' => 'E-mail ou senha incorretos.',
            ],

            // ================= ADMIN: DASHBOARD =================
            'admin_dashboard' => [
                'titulo' => 'Dashboard — Gostosuras',
                'titulo.pagina' => 'Visão geral de hoje',
                'metrica.faturamento_hoje' => 'Faturamento hoje',
                'metrica.pedidos_hoje' => 'Pedidos hoje',
                'metrica.ticket_hoje' => 'Ticket médio hoje',
                'metrica.faturamento_mes' => 'Faturamento do mês',
                'metrica.pedidos_mes' => ':qtd pedidos no mês',
                'grafico.titulo' => 'Últimos 14 dias',
                'grafico.pedidos' => 'pedidos',
                'status.titulo' => 'Pedidos por status',
                'recentes.titulo' => 'Pedidos recentes',
                'estoque.titulo' => 'Estoque precisando de atenção',
                'estoque.ok' => 'Tudo sob controle por aqui.',
                'botao.previsao' => 'Ver previsão de produção por horário',
            ],

            // ================= ADMIN: PRODUTOS =================
            'admin_produtos' => [
                'titulo' => 'Produtos e estoque — Gostosuras',
                'titulo.pagina' => 'Produtos e estoque',
                'busca.placeholder' => 'Buscar por nome ou categoria...',
                'botao.buscar' => 'Buscar',
                'botao.salvar_estoque' => 'Salvar',
                'filtro.critico' => 'Estoque baixo (:qtd)',
                'filtro.esgotado' => 'Esgotados',
                'nota.estoque_vazio' => 'Regra da loja: o produto só é vendido com quantidade maior que zero. Sem quantidade definida, ele fica indisponível na vitrine.',
                'tabela.produto' => 'Produto',
                'tabela.categoria' => 'Categoria',
                'tabela.preco' => 'Preço',
                'tabela.estoque' => 'Estoque',
                'tabela.minimo' => 'Mínimo',
                'tabela.sem_controle' => '— sem controle —',
                'tabela.vitrine' => 'Vitrine',
                'tabela.destaque' => 'Destaque',
                'lista.vazia' => 'Nenhum produto cadastrado ainda.',
                'erro.estoque_invalido' => 'Informe um número inteiro.',
                'erro.imagem_invalida' => 'O arquivo precisa ser uma imagem JPG, PNG ou WEBP.',
                'erro.imagem_grande' => 'A imagem passa de 4 MB — escolha uma mais leve.',
                'sucesso.atualizado' => 'Produto atualizado!',
                'sucesso.criado' => 'Produto criado e disponível na vitrine!',
                'sucesso.removido' => 'Produto removido — é possível restaurá-lo pela Auditoria.',
                'botao.novo' => '+ Novo produto',
                'botao.editar' => 'Editar',
                'botao.confirmar_remover' => 'Remover este produto? Ele sai da vitrine, mas pode ser restaurado pela Auditoria.',
                'tabela.acoes' => 'Ações',
                'titulo.form' => 'Produto — Gostosuras',
                'form.titulo_novo' => 'Novo produto',
                'form.titulo_editar' => 'Editar produto',
                'form.secao.identificacao' => 'Identificação',
                'form.secao.imagem' => 'Imagem do card',
                'form.secao.estoque' => 'Preço e estoque',
                'form.secao.exibicao' => 'Exibição na vitrine',
                'form.campo.nome' => 'Nome do produto',
                'form.campo.categoria' => 'Categoria',
                'form.campo.preco' => 'Preço (R$)',
                'form.campo.descricao' => 'Descrição — aparece no card da vitrine',
                'form.campo.imagem' => 'Imagem',
                'form.trocar_imagem' => 'Trocar imagem (opcional)',
                'form.campo.estoque' => 'Quantidade em estoque (obrigatória para vender)',
                'form.campo.minimo' => 'Estoque mínimo (alerta)',
                'form.campo.ativo' => 'Visível na vitrine',
                'form.campo.destaque' => 'Aparece nos Destaques da vitrine',
                'form.selecione' => 'Selecione...',
                'form.exemplo.nome' => 'Ex.: Brigadeiro de Pistache',
                'form.exemplo.descricao' => 'Ex.: Massa cremosa de pistache com cobertura crocante de chocolate branco.',
                'form.botao.salvar' => 'Salvar produto',
                'erro.campo_obrigatorio' => 'Preencha este campo.',
                'erro.categoria' => 'Escolha uma categoria válida.',
                'erro.numero' => 'Informe um número válido.',
                'form.secao.complementos' => 'Personalizações (opcional)',
                'form.nota.complementos' => 'Deixe o cliente escolher adicionais (pagos) ou remoções (grátis) — ex.: cobertura +R$2,00 ou "sem leite condensado".',
                'form.botao_adicionar_complemento' => '+ Adicionar personalização',
                'form.comp_tipo' => 'Tipo',
                'form.comp_adicional' => 'Adicional (pago)',
                'form.comp_remocao' => 'Remoção (grátis)',
                'form.comp_nome' => 'Nome',
                'form.comp_preco' => 'Preço (R$)',
                'form.comp_exemplo' => 'Ex.: Cobertura de chocolate',
                'form.remover_complemento' => 'Remover',
            ],

            // ================= ADMIN: PEDIDOS =================
            'admin_pedidos' => [
                'titulo' => 'Pedidos — Gostosuras',
                'titulo.pagina' => 'Pedidos',
                'titulo.detalhe' => 'Pedido :codigo — Gostosuras',
                'busca.placeholder' => 'Código, cliente ou telefone...',
                'filtro.todos' => 'Todos',
                'tabela.codigo' => 'Código',
                'tabela.quando' => 'Quando',
                'tabela.cliente' => 'Cliente',
                'tabela.tipo' => 'Tipo',
                'tabela.pagamento' => 'Pagamento',
                'tabela.itens' => 'Itens',
                'tabela.total' => 'Total',
                'tabela.status' => 'Status',
                'lista.vazia' => 'Nenhum pedido encontrado.',
                'detalhe.resumo_titulo' => 'Resumo',
                'detalhe.item' => 'Item',
                'detalhe.qtd' => 'Qtd',
                'detalhe.unitario' => 'Unitário',
                'detalhe.subtotal' => 'Subtotal',
                'detalhe.troco' => 'Levar troco para :valor',
                'detalhe.status_titulo' => 'Atualizar status',
                'detalhe.cancelar_aviso' => 'Cancelar devolve os itens ao estoque automaticamente.',
                'detalhe.cliente_titulo' => 'Cliente',
                'detalhe.conta_vinculada' => 'Pedido vinculado a uma conta de cliente.',
                'detalhe.chave_titulo' => 'Chave de segurança',
                'detalhe.chave_texto' => 'Na entrega/retirada, peça ao cliente a chave de segurança cadastrada na conta dele e confirme antes de marcar como entregue.',
                'nota.desligada' => 'A emissão de nota está desligada — ative em Configurações.',
                'nota.sem_empresa' => 'Preencha o CNPJ da empresa em Configurações antes de gerar a nota.',
                'nota.ja_existe' => 'Este pedido já tem uma nota fiscal registrada.',
                'nota.pendente_cert' => 'Pendente de transmissão à SEFAZ.',
                'nota.pendente_sem_cert' => 'Pendente: configure o certificado digital A1 (NFE_CERT_PATH e NFE_CERT_SENHA no .env) para transmitir.',
                'nota.criada' => 'Nota fiscal registrada como PENDENTE para este pedido.',
                'nota.titulo' => 'Nota fiscal',
                'nota.pagamento' => 'Pagamento online',
                'nota.pagamento_pago' => 'Pago',
                'nota.pagamento_pendente' => 'Pendente',
                'nota.sem_nota' => 'Nenhuma nota gerada para este pedido.',
                'nota.botao_gerar' => 'Gerar NF',
                'sucesso.status' => 'Status atualizado!',
                'whatsapp.titulo' => 'WhatsApp do cliente',
                'whatsapp.nota' => 'Encaminhe o resumo do pedido ao cliente para confirmar. Usa o WhatsApp da loja quando configurado; senão, gera um link.',
                'whatsapp.botao' => 'Encaminhar pedido no WhatsApp',
                'whatsapp.abrir_link' => 'Abrir no WhatsApp',
                'whatsapp.sem_telefone' => 'Este pedido não tem telefone de contato.',
                'whatsapp.link_gerado' => 'WhatsApp não configurado — abra o link abaixo para enviar o pedido.',
                'whatsapp.enviado' => 'Pedido encaminhado ao cliente pelo WhatsApp!',
                'whatsapp.fallback' => 'Use o link abaixo para enviar manualmente.',
                'whatsapp.pedido_rotulo' => 'Pedido',
                'whatsapp.cliente' => 'Cliente',
                'whatsapp.telefone' => 'Telefone',
                'whatsapp.tipo' => 'Tipo',
                'whatsapp.pagamento' => 'Pagamento',
                'whatsapp.endereco' => 'Endereço',
                'whatsapp.total' => 'Total',
            ],

            // ================= ADMIN: RELATÓRIOS =================
            'admin_relatorios' => [
                'titulo' => 'Relatórios — Gostosuras',
                'titulo.pagina' => 'Relatórios',
                'campo.de' => 'De',
                'campo.ate' => 'Até',
                'botao.aplicar' => 'Aplicar período',
                'botao.exportar' => '⬇ Exportar CSV',
                'botao.mensal' => 'Relatório mensal (PDF)',
                'botao.simples_vendas' => 'Relatório simples de vendas',
                'botao.simples_produtos' => 'Relatório simples de produtos',
                'aba.vendas' => 'Vendas',
                'aba.produtos' => 'Produtos',
                'aba.horarios' => 'Horários',
                'aba.pagamentos' => 'Pagamentos',
                'aba.entregas' => 'Entregas',
                'aba.estoque' => 'Estoque',
                'vendas.faturamento' => 'Faturamento no período',
                'vendas.pedidos' => 'Pedidos',
                'vendas.ticket' => 'Ticket médio',
                'vendas.taxas' => 'Taxas de entrega somadas',
                'vendas.clientes' => 'Clientes distintos (com conta)',
                'vendas.por_dia' => 'Vendas por dia',
                'produtos.titulo' => 'Mais vendidos no período',
                'produtos.vazio' => 'Nenhuma venda registrada neste período.',
                'produtos.quantidade' => 'Qtd vendida',
                'produtos.faturamento' => 'Faturamento',
                'horarios.titulo' => 'Quanto produzir em cada horário',
                'horarios.explicacao' => 'Média de itens vendidos em cada hora do dia, considerando o período escolhido, mais uma margem de segurança de :margem%. Use como guia de produção diária.',
                'horarios.vazio' => 'Ainda sem vendas suficientes para calcular a previsão.',
                'horarios.hora' => 'Hora',
                'horarios.total_periodo' => 'Itens no período',
                'horarios.media_dia' => 'Média por dia ativo',
                'horarios.sugestao' => 'Produzir (com margem)',
                'horarios.nota_margem' => 'Para ajustar a margem de segurança, altere a configuração "margem_producao" da loja.',
                'pagamentos.titulo' => 'Formas de pagamento no período',
                'pagamentos.vazio' => 'Nenhuma venda registrada neste período.',
                'pagamentos.fatia' => 'Fatia',
                'entregas.pedidos_no_periodo' => 'pedidos no período',
                'estoque.titulo' => 'Estoque crítico ou esgotado',
                'estoque.repor' => 'Repor',
            ],

            // ================= ADMIN: RELATÓRIO MENSAL =================
            'admin_mensal' => [
                'titulo' => 'Relatório mensal — Gostosuras',
                'titulo.pagina' => 'Relatório mensal',
                'subtitulo' => 'Relatório mensal de vendas e produtos',
                'botao.ir' => 'Ir',
                'botao.pdf' => 'Exportar PDF',
                'resumo.faturamento' => 'Faturamento do mês',
                'secao.vendas' => 'Vendas dia a dia',
                'coluna.dia' => 'Dia',
                'coluna.acumulado' => 'Acumulado do mês',
                'coluna.total' => 'TOTAL DO MÊS',
                'secao.produtos' => 'Produtos vendidos no mês',
                'rodape' => 'Documento gerado pelo painel Gostosuras — valores consideram pedidos não cancelados.',
            ],

            // ================= ADMIN: RELATÓRIO SIMPLES =================
            'admin_simples' => [
                'vendas.titulo' => 'Relatório de vendas',
                'produtos.titulo' => 'Relatório de produtos',
                'coluna.produto' => 'Produto',
                'coluna.quantidade' => 'Quantidade',
                'coluna.valor_venda' => 'Valor de venda',
                'coluna.valor_unitario' => 'Valor unitário',
                'coluna.total' => 'Total',
                'coluna.total_geral' => 'TOTAL GERAL',
                'botao.csv' => 'Exportar CSV',
                'botao.pdf' => 'Exportar PDF (imprimir)',
                'trocar_vendas' => 'Ver como relatório de vendas',
                'trocar_produtos' => 'Ver como relatório de produtos',
            ],

            // ================= WHATSAPP (API oficial) =================
            'whatsapp' => [
                'erro.conexao' => 'Não foi possível conectar ao WhatsApp agora — tente de novo.',
                'erro.token' => 'Token do WhatsApp inválido ou expirado — confira em Configurações.',
                'erro.janela' => 'Fora da janela de 24h deste cliente — a Meta só aceita template aprovado nesse caso.',
                'erro.phone_id' => 'Phone Number ID do WhatsApp não encontrado — confira em Configurações.',
                'erro.falha' => 'O WhatsApp recusou o envio para este número.',
            ],
        ];

        foreach ($textos as $pagina => $chaves) {
            foreach ($chaves as $chave => $valor) {
                Texto::updateOrCreate(
                    ['loja_id' => null, 'pagina' => $pagina, 'chave' => $chave],
                    ['valor' => $valor]
                );
            }
        }
    }
}
